#!/bin/bash
exec < /dev/tty

# Get the current branch name
branch_name=$(git branch | grep "*" | sed "s/\* //")

if [[ $branch_name != "master" ]]; then
    echo 'Not in master, post-merge will not be executed'
    exit 0
fi

echo 'Replacing SNAPSHOT by RELEASE'
# Replacing SNAPSHOT by RELEASE
sed -i '' 's/SNAPSHOT/RELEASE/g' pom.xml

# commit and push of the upgraded pom
echo 'Commit and push of the upgraded pom'
git add pom.xml
git commit -m 'upgrading SNAPSHOT to next RELEASE'
git push origin $branch_name

# creating and pushing a new tag
tag_version = $(sed -n 's:.*<version>\(.*\)</version>.*:\1:p' pom.xml)
echo 'Creating tag: '$tag_tag_version
git tag -a v$tag_version -m \'$tag_version\'
git push origin v$tag_version