#!/bin/bash
exec < /dev/tty

#fails if any action were marked as failed
set -e

#taking the actions to execute from the "pre-push-actions"
input="git-hooks/pre-push-actions"
while read line; do $line; done < $input; echo $line